# Generated by pixi-build-ros.
# DO NOT EDIT — see crates/pixi_build_ros/templates/build_ament_cargo.sh in the
# pixi-build-ros source.

set -eo pipefail
# An ignored SIGPIPE survives exec, so every compiler, ninja and cmake process
# below inherits it and sees EPIPE on a doomed log write instead of dying. A
# build that has already compiled and installed must not fail on its own output.
trap '' PIPE

# Stage source into a work-dir-local copy and drop a synthesized package.xml
# alongside Cargo.toml. cargo-ament-build copies package.xml into
# share/<pkg>/ at install time and errors if it isn't present.
#
# In pixi-native mode @SRC_DIR@ is the user's manifest dir and $PWD is
# <SRC_DIR>/.pixi/build/work/.../work — STAGE_DIR therefore sits inside
# @SRC_DIR@ and a plain `cp -a SRC_DIR/. STAGE_DIR/` recurses into itself.
# Tar with excludes side-steps that and skips junk we don't want in the build.
STAGE_DIR="$PWD/src_stage"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
tar -C "@SRC_DIR@" --exclude=./.pixi --exclude=./.git --exclude=./.cargo --exclude=./target -cf - . | tar -C "$STAGE_DIR" -xf -

cat > "$STAGE_DIR/package.xml" <<'__PIXI_NATIVE_PACKAGE_XML__'
@PACKAGE_XML_CONTENT@
__PIXI_NATIVE_PACKAGE_XML__

pushd "$STAGE_DIR"

export ROS_DISTRO=@DISTRO@
export AMENT_PREFIX_PATH="$PREFIX"
export CMAKE_PREFIX_PATH="$PREFIX"

# Rust 1.85+ defaults to the `wild` linker which conda's gcc rejects.
# Force cargo to link via the conda C compiler.
if [ -n "${CC:-}" ]; then
  export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="${CC}"
  export RUSTFLAGS="-C linker=${CC} ${RUSTFLAGS:-}"
fi

# Message packages ship their generated Rust bindings under
# $PREFIX/share/<pkg>/rust, not on crates.io. The rclrs-bound message crates
# depend on each other by bare name (e.g. `builtin_interfaces = "*"`), so
# without intervention cargo resolves them from crates.io — where they are
# absent or present only as yanked stubs — and the build fails. Generate a
# [patch.crates-io] table redirecting every in-prefix binding to its local
# path so cargo resolves them from the build environment. Patches for packages
# not in this crate's graph are unused and warned about, but harmless.
mkdir -p "$STAGE_DIR/.cargo"
CARGO_PATCH_CONFIG="$STAGE_DIR/.cargo/config.toml"
for cargo_toml in "$PREFIX"/share/*/rust/Cargo.toml; do
  [ -e "$cargo_toml" ] || continue
  crate_dir="$(dirname "$cargo_toml")"
  crate_name="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$cargo_toml" | head -n1)"
  [ -n "$crate_name" ] || continue
  {
    printf '[patch.crates-io.%s]\n' "$crate_name"
    printf 'path = "%s"\n\n' "$crate_dir"
  } >> "$CARGO_PATCH_CONFIG"
done

# cargo-ament-build wraps `cargo build` (or `cargo check` for pure libraries)
# and lays down the ament install layout under --install-base. Source code is
# copied to share/<pkg>/rust/ so downstream Rust crates can resolve path
# dependencies via AMENT_PREFIX_PATH.
#
# `--release` is passed both before and after `--`: cargo-ament-build's own
# `--release` flag only switches where it looks for the built artifact
# (target/release/ vs target/debug/) — it is NOT forwarded to the inner
# `cargo build` call. Without the second `--release`, cargo builds the dev
# profile and the post-build copy step fails with
# `Failed to copy binary from 'target/release/<pkg>'`.
cargo ament-build --install-base "$PREFIX" --release -- --release --locked --offline || \
  cargo ament-build --install-base "$PREFIX" --release -- --release

# Install activation/deactivation scripts so that `pixi shell` / `pixi run`
# environments get the same [patch.crates-io] cargo config that the build
# environment uses. Without this, `cargo check` in a dev shell fails because
# ROS message crates (std_msgs, builtin_interfaces, …) only exist as local
# sources under $CONDA_PREFIX/share/*/rust/, not on crates.io.
_ACTIVATE_DIR="$PREFIX/etc/conda/activate.d"
_DEACTIVATE_DIR="$PREFIX/etc/conda/deactivate.d"
mkdir -p "$_ACTIVATE_DIR" "$_DEACTIVATE_DIR"

cat > "$_ACTIVATE_DIR/rust-ament-cargo-patches.sh" << 'ACTIVATE'
#!/bin/bash
# Generated by pixi-build-ros (ament_cargo).
# Generates .cargo/config.toml with [patch.crates-io] entries so that cargo
# can resolve ROS message crates from the conda prefix instead of crates.io.
_PIXI_CARGO_PATCHES_MARKER="# pixi-build-ros:ament-cargo-patches"

if [ -z "${CONDA_PREFIX:-}" ]; then
  return 0 2>/dev/null || exit 0
fi

# Only act when inside a pixi project that has a Cargo.toml.
if [ -z "${PIXI_PROJECT_ROOT:-}" ] || [ ! -f "$PIXI_PROJECT_ROOT/Cargo.toml" ]; then
  return 0 2>/dev/null || exit 0
fi

_cfg="$PIXI_PROJECT_ROOT/.cargo/config.toml"

# If the file exists but wasn't generated by us, leave it alone.
if [ -f "$_cfg" ] && ! head -n1 "$_cfg" | grep -qF "$_PIXI_CARGO_PATCHES_MARKER"; then
  return 0 2>/dev/null || exit 0
fi

mkdir -p "$PIXI_PROJECT_ROOT/.cargo"
{
  printf '%s\n' "$_PIXI_CARGO_PATCHES_MARKER"
  printf '# DO NOT EDIT — regenerated on every pixi environment activation.\n\n'
  for _ct in "$CONDA_PREFIX"/share/*/rust/Cargo.toml; do
    [ -e "$_ct" ] || continue
    _cd="$(dirname "$_ct")"
    _cn="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$_ct" | head -n1)"
    [ -n "$_cn" ] || continue
    printf '[patch.crates-io.%s]\npath = "%s"\n\n' "$_cn" "$_cd"
  done
} > "$_cfg"

unset _cfg _ct _cd _cn _PIXI_CARGO_PATCHES_MARKER
ACTIVATE

cat > "$_DEACTIVATE_DIR/rust-ament-cargo-patches.sh" << 'DEACTIVATE'
#!/bin/bash
# Generated by pixi-build-ros (ament_cargo).
_PIXI_CARGO_PATCHES_MARKER="# pixi-build-ros:ament-cargo-patches"

if [ -z "${PIXI_PROJECT_ROOT:-}" ]; then
  return 0 2>/dev/null || exit 0
fi

_cfg="$PIXI_PROJECT_ROOT/.cargo/config.toml"
if [ -f "$_cfg" ] && head -n1 "$_cfg" | grep -qF "$_PIXI_CARGO_PATCHES_MARKER"; then
  rm -f "$_cfg"
  rmdir "$PIXI_PROJECT_ROOT/.cargo" 2>/dev/null || true
fi

unset _cfg _PIXI_CARGO_PATCHES_MARKER
DEACTIVATE
